name: qr_attendance_manager
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # [추가] 날짜 및 시간 포맷팅 (출석 리스트용)
  intl: ^0.20.2

  # [정유림님] 신청자와 출석자 비교 및 QR 스캔
  firebase_database: ^12.2.0
  mobile_scanner: ^7.2.0
  permission_handler: ^12.0.1

  # [김민겸님] Firebase 핵심 패키지
  firebase_core: ^4.6.0
  cloud_firestore: ^6.2.0
  firebase_auth: ^6.3.0

  # [김민수님] 참여율 그래프용
  fl_chart: ^0.68.0

  # [조태현님] 위치 및 오프라인 저장용/QR생성
  geolocator: ^12.0.0
  shared_preferences: ^2.2.3
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # 스플래시 화면 설정
  flutter_native_splash: ^2.4.0

# 스플래시 상세 설정
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/school_logo.png
  android_12:
    image: assets/images/school_logo.png
    color: "#ffffff" # 안드로이드 12용 배경색 명시

flutter:
  uses-material-design: true

  assets:
    - assets/images/school_logo.png