// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3I2vjH5MkujNgkQegPLnwVn7jk-T17j4',
    appId: '1:699483259444:web:362b72e3169e40d2720061',
    messagingSenderId: '699483259444',
    projectId: 'qr-attendance-manager-752a6',
    authDomain: 'qr-attendance-manager-752a6.firebaseapp.com',
    storageBucket: 'qr-attendance-manager-752a6.firebasestorage.app',
    measurementId: 'G-K8KVWZH2M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU315B4EDu1lktspodO8CNA8zYrrqnInA',
    appId: '1:699483259444:android:6f8c7a709e7e730c720061',
    messagingSenderId: '699483259444',
    projectId: 'qr-attendance-manager-752a6',
    storageBucket: 'qr-attendance-manager-752a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcem1lD5oQAIEsd3B3Sz2H_DxmqlDih5w',
    appId: '1:699483259444:ios:9b6a6790ddf4a885720061',
    messagingSenderId: '699483259444',
    projectId: 'qr-attendance-manager-752a6',
    storageBucket: 'qr-attendance-manager-752a6.firebasestorage.app',
    iosBundleId: 'com.example.qrAttendanceManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcem1lD5oQAIEsd3B3Sz2H_DxmqlDih5w',
    appId: '1:699483259444:ios:9b6a6790ddf4a885720061',
    messagingSenderId: '699483259444',
    projectId: 'qr-attendance-manager-752a6',
    storageBucket: 'qr-attendance-manager-752a6.firebasestorage.app',
    iosBundleId: 'com.example.qrAttendanceManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3I2vjH5MkujNgkQegPLnwVn7jk-T17j4',
    appId: '1:699483259444:web:e7f4ee034af5c60e720061',
    messagingSenderId: '699483259444',
    projectId: 'qr-attendance-manager-752a6',
    authDomain: 'qr-attendance-manager-752a6.firebaseapp.com',
    storageBucket: 'qr-attendance-manager-752a6.firebasestorage.app',
    measurementId: 'G-WF2JS25LY2',
  );
}
